<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('doctors')->insert([
            [
                'first_name' => 'Maria Clara',
                'middle_name' => 'Luna',
                'last_name' => 'Sarmiento',
                'specialization' => 'Cardiology',
                'qualifications' => 'MD, FPCP, FPCC',
                'license' => 'PRC-0102345',
                'contact_number' => '0917-555-1234',
                'email' => 'm.sarmiento@clinic.ph',
                'bio' => 'Specialist in adult cardiology and heart failure management with 15 years of experience.',
                'assigned_clinic' => 'Heart & Wellness Center - Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Jose',
                'middle_name' => 'Rizal',
                'last_name' => 'Mercado',
                'specialization' => 'Ophthalmology',
                'qualifications' => 'MD, DPBO',
                'license' => 'PRC-0987654',
                'contact_number' => '0918-444-5678',
                'email' => 'j.mercado@eyecare.ph',
                'bio' => 'Expert in cataract surgery and corrective vision procedures.',
                'assigned_clinic' => 'Davao Eye Specialists',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Ana',
                'middle_name' => 'Patricia',
                'last_name' => 'Reyes',
                'specialization' => 'Pediatrics',
                'qualifications' => 'MD, FPPS',
                'license' => 'PRC-0556677',
                'contact_number' => '0922-333-4444',
                'email' => 'ana.reyes@pediatrics.ph',
                'bio' => 'Dedicated to comprehensive childcare from infancy through adolescence.',
                'assigned_clinic' => 'St. Jude Childrens Clinic',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Mark',
                'middle_name' => 'Anthony',
                'last_name' => 'Dela Cruz',
                'specialization' => 'Orthopedics',
                'qualifications' => 'MD, FPOA',
                'license' => 'PRC-0334455',
                'contact_number' => '0945-888-9999',
                'email' => 'mark.delacruz@bones.ph',
                'bio' => 'Specializes in sports medicine and joint replacement surgery.',
                'assigned_clinic' => 'Orthopedic Care Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Elena',
                'middle_name' => 'Grace',
                'last_name' => 'Pascual',
                'specialization' => 'Dermatology',
                'qualifications' => 'MD, FPDS',
                'license' => 'PRC-0112233',
                'contact_number' => '0908-111-2222',
                'email' => 'elena.pascual@skin.ph',
                'bio' => 'Board-certified dermatologist focusing on clinical and cosmetic skin health.',
                'assigned_clinic' => 'Dermacare Metro',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Ricardo',
                'middle_name' => 'P.',
                'last_name' => 'Villanueva',
                'specialization' => 'Internal Medicine',
                'qualifications' => 'MD, FPCP',
                'license' => 'PRC-0778899',
                'contact_number' => '0915-222-3333',
                'email' => 'r.villanueva@health.ph',
                'bio' => 'Focused on long-term wellness and management of chronic adult illnesses.',
                'assigned_clinic' => 'City General Outpatient',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Sofia',
                'middle_name' => 'Isabelle',
                'last_name' => 'Santos',
                'specialization' => 'Obstetrics & Gynecology',
                'qualifications' => 'MD, FPOGS',
                'license' => 'PRC-0445566',
                'contact_number' => '0919-666-7777',
                'email' => 'sofia.santos@womens.ph',
                'bio' => 'Compassionate care for high-risk pregnancies and reproductive health.',
                'assigned_clinic' => 'Maternity Care Center',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Antonio',
                'middle_name' => 'G.',
                'last_name' => 'Mendoza',
                'specialization' => 'Neurology',
                'qualifications' => 'MD, FPNA',
                'license' => 'PRC-0223344',
                'contact_number' => '0933-999-0000',
                'email' => 'a.mendoza@neuro.ph',
                'bio' => 'Specialist in stroke management and neurological disorders.',
                'assigned_clinic' => 'Brain & Nerve Institute',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Liza',
                'middle_name' => 'Jane',
                'last_name' => 'Bautista',
                'specialization' => 'Endocrinology',
                'qualifications' => 'MD, FPCP, FPSEM',
                'license' => 'PRC-0889900',
                'contact_number' => '0942-777-8888',
                'email' => 'liza.bautista@hormone.ph',
                'bio' => 'Expert in diabetes management and thyroid disorders.',
                'assigned_clinic' => 'Endocrine Specialists Inc.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Fernando',
                'middle_name' => 'Miguel',
                'last_name' => 'Torres',
                'specialization' => 'Gastroenterology',
                'qualifications' => 'MD, FPCP, FPSG',
                'license' => 'PRC-0667788',
                'contact_number' => '0927-444-1111',
                'email' => 'f.torres@digestive.ph',
                'bio' => 'Dedicated to the diagnosis and treatment of digestive tract conditions.',
                'assigned_clinic' => 'GI Health Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Carmen',
                'middle_name' => 'E.',
                'last_name' => 'Dizon',
                'specialization' => 'Psychiatry',
                'qualifications' => 'MD, FPPA',
                'license' => 'PRC-0990011',
                'contact_number' => '0917-888-2222',
                'email' => 'c.dizon@mindcare.ph',
                'bio' => 'Promoting mental health wellness through holistic psychiatric care.',
                'assigned_clinic' => 'MindCare Wellness Center',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Emilio',
                'middle_name' => 'S.',
                'last_name' => 'Aguinaldo',
                'specialization' => 'Urology',
                'qualifications' => 'MD, FPUA',
                'license' => 'PRC-0332211',
                'contact_number' => '0905-333-7777',
                'email' => 'e.aguinaldo@urology.ph',
                'bio' => 'Specialist in kidney health and urinary tract surgical procedures.',
                'assigned_clinic' => 'UroLink Medical',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Paola',
                'middle_name' => 'V.',
                'last_name' => 'Gomez',
                'specialization' => 'ENT',
                'qualifications' => 'MD, FPSO-HNS',
                'license' => 'PRC-0443322',
                'contact_number' => '0916-555-9999',
                'email' => 'p.gomez@entclinic.ph',
                'bio' => 'Treatment for ear, nose, throat, and head-neck surgeries.',
                'assigned_clinic' => 'ENT Care South',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Victor',
                'middle_name' => 'L.',
                'last_name' => 'Magbanua',
                'specialization' => 'General Surgery',
                'qualifications' => 'MD, FPCS',
                'license' => 'PRC-0554433',
                'contact_number' => '0912-111-0000',
                'email' => 'v.magbanua@surgery.ph',
                'bio' => 'Specialist in minimally invasive laparoscopic surgeries.',
                'assigned_clinic' => 'City Surgical Group',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Grace',
                'middle_name' => 'M.',
                'last_name' => 'Tan',
                'specialization' => 'Pulmonology',
                'qualifications' => 'MD, FPCP, FPCCP',
                'license' => 'PRC-0665544',
                'contact_number' => '0918-222-1111',
                'email' => 'g.tan@lungcare.ph',
                'bio' => 'Expert in respiratory health and asthma management.',
                'assigned_clinic' => 'Lung Center Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Benjamin',
                'middle_name' => 'H.',
                'last_name' => 'Lopez',
                'specialization' => 'Nephrology',
                'qualifications' => 'MD, FPCP, FPSN',
                'license' => 'PRC-0776655',
                'contact_number' => '0920-333-2222',
                'email' => 'b.lopez@renal.ph',
                'bio' => 'Specialized in dialysis and kidney transplant medicine.',
                'assigned_clinic' => 'Renal Health Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Theresa',
                'middle_name' => 'K.',
                'last_name' => 'Ang',
                'specialization' => 'Rheumatology',
                'qualifications' => 'MD, FPCP, FPRA',
                'license' => 'PRC-0887766',
                'contact_number' => '0921-444-3333',
                'email' => 't.ang@joints.ph',
                'bio' => 'Expert in arthritis and autoimmune inflammatory diseases.',
                'assigned_clinic' => 'Joint & Bone Center',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Christopher',
                'middle_name' => 'P.',
                'last_name' => 'Ong',
                'specialization' => 'Infectious Disease',
                'qualifications' => 'MD, FPCP, PSMID',
                'license' => 'PRC-0998877',
                'contact_number' => '0922-555-4444',
                'email' => 'c.ong@idclinic.ph',
                'bio' => 'Specialist in complex infections and tropical medicine.',
                'assigned_clinic' => 'Health Guard Davao',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Monica',
                'middle_name' => 'S.',
                'last_name' => 'Javier',
                'specialization' => 'Oncology',
                'qualifications' => 'MD, FPCP, FPSMO',
                'license' => 'PRC-0119988',
                'contact_number' => '0923-666-5555',
                'email' => 'm.javier@cancercenter.ph',
                'bio' => 'Medical oncologist specializing in targeted chemotherapy treatments.',
                'assigned_clinic' => 'Hope Cancer Institute',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'first_name' => 'Leonardo',
                'middle_name' => 'D.',
                'last_name' => 'Pineda',
                'specialization' => 'Anesthesiology',
                'qualifications' => 'MD, DPBA',
                'license' => 'PRC-0220099',
                'contact_number' => '0924-777-6666',
                'email' => 'l.pineda@anesthesia.ph',
                'bio' => 'Pain management and perioperative medical care specialist.',
                'assigned_clinic' => 'Davao Medical Hub',
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}