<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('patients')->insert([
            [
                'first_name' => 'John',
                'middle_name' => 'Quincy',
                'last_name' => 'Doe',
                'allergy' => 'Penicillin, Peanuts',
                'chronic_conditions' => 'Hypertension',
                'past_surgeries' => 'Appendectomy (2015)',
                'family_medical_history' => 'Type 2 Diabetes (Father)',
                'blood_group' => 'O+',
                'emergency_contact_name' => 'Jane Doe',
                'emergency_contact_phone' => '09123456789',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'first_name' => 'Alice',
                'middle_name' => null,
                'last_name' => 'Smith',
                'allergy' => null,
                'chronic_conditions' => 'Asthma',
                'past_surgeries' => null,
                'family_medical_history' => 'None',
                'blood_group' => 'A-',
                'emergency_contact_name' => 'Robert Smith',
                'emergency_contact_phone' => '09987654321',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'first_name' => 'Michael',
                'middle_name' => 'James',
                'last_name' => 'Garcia',
                'allergy' => 'Aspirin',
                'chronic_conditions' => 'Type 1 Diabetes',
                'past_surgeries' => 'Knee Surgery (2022)',
                'family_medical_history' => 'Heart Disease (Grandfather)',
                'blood_group' => 'B+',
                'emergency_contact_name' => 'Elena Garcia',
                'emergency_contact_phone' => '09171234567',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Sophia',
                'middle_name' => 'Marie',
                'last_name' => 'Villanueva',
                'allergy' => 'Latex',
                'chronic_conditions' => 'None',
                'past_surgeries' => 'Tonsillectomy (2010)',
                'family_medical_history' => 'Hypertension',
                'blood_group' => 'AB-',
                'emergency_contact_name' => 'Marco Villanueva',
                'emergency_contact_phone' => '09205558888',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'David',
                'middle_name' => null,
                'last_name' => 'Tan',
                'allergy' => 'Shellfish',
                'chronic_conditions' => 'Gout',
                'past_surgeries' => null,
                'family_medical_history' => 'Stroke (Mother)',
                'blood_group' => 'O-',
                'emergency_contact_name' => 'Linda Tan',
                'emergency_contact_phone' => '09451112222',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Isabella',
                'middle_name' => 'Grace',
                'last_name' => 'Lopez',
                'allergy' => 'Dust Mites',
                'chronic_conditions' => 'Anemia',
                'past_surgeries' => 'C-Section (2019)',
                'family_medical_history' => 'None',
                'blood_group' => 'B-',
                'emergency_contact_name' => 'Ricardo Lopez',
                'emergency_contact_phone' => '09187773333',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Gabriel',
                'middle_name' => 'Lucas',
                'last_name' => 'Santos',
                'allergy' => 'None',
                'chronic_conditions' => 'Hypertension',
                'past_surgeries' => 'Gallbladder Removal (2021)',
                'family_medical_history' => 'Diabetes',
                'blood_group' => 'A+',
                'emergency_contact_name' => 'Maria Santos',
                'emergency_contact_phone' => '09084445555',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Catherine',
                'middle_name' => 'Anne',
                'last_name' => 'Reyes',
                'allergy' => 'Ibuprofen',
                'chronic_conditions' => 'Migraine',
                'past_surgeries' => null,
                'family_medical_history' => 'Breast Cancer (Aunt)',
                'blood_group' => 'AB+',
                'emergency_contact_name' => 'Antonio Reyes',
                'emergency_contact_phone' => '09159990000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Kevin',
                'middle_name' => null,
                'last_name' => 'Dela Cruz',
                'allergy' => 'Dairy',
                'chronic_conditions' => 'None',
                'past_surgeries' => 'LASIK (2018)',
                'family_medical_history' => 'None',
                'blood_group' => 'O+',
                'emergency_contact_name' => 'Sarah Dela Cruz',
                'emergency_contact_phone' => '09226667777',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Beatrix',
                'middle_name' => 'Pau',
                'last_name' => 'Lim',
                'allergy' => 'Sulkha Drugs',
                'chronic_conditions' => 'Thyroid Disorder',
                'past_surgeries' => null,
                'family_medical_history' => 'Arthritis',
                'blood_group' => 'B+',
                'emergency_contact_name' => 'Wilson Lim',
                'emergency_contact_phone' => '09334449999',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}